MVC5Template/MVC5Template/Areas/Admin/Controllers/UserController.cs
using MVC5Template.Dapper;
using MVC5Template.Extensions;
using MVC5Template.Models;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace MVC5Template.Areas.Admin.Controllers
{
    public class UserController : SupportContoller
    {
        public ActionResult Index()
        {
            IEnumerable<User> result = DapperManager.Query<User>(
                "MVC5TemplateServer",
                "SELECT * FROM [dbo].[User]");

            return View(result);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserID,Password,FamilyName,FirstName,Birthday,Sex,MobilePhone,PostalCode,Prefectures,City,Address1,Address2,Apartment")] User user)
        {
            if (ModelState.IsValid)
            {
                int result = DapperManager.Execute(
                    "MVC5TemplateServer",
                    "INSERT [dbo].[User] (UserID, Password, FamilyName, FirstName, Birthday, Sex, MobilePhone, PostalCode, Prefectures, City, Address1, Address2, Apartment) VALUES (@UserID, @Password, @FamilyName, @FirstName, @Birthday, @Sex, @MobilePhone, @PostalCode, @Prefectures, @City, @Address1, @Address2, @Apartment)", user);

                return RedirectToAction("Index");
            }
            return View(user);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                IEnumerable<User> user = DapperManager.Query<User>("MVC5TemplateServer", "SELECT * FROM [dbo].[User] WHERE UserID = @UserID", new { UserID = id });
                if (user == null)
                {
                    return HttpNotFound();
                }
                return View(user.FirstOrDefault());
            }
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            User user = DapperManager.Query<User>("MVC5TemplateServer",
            "SELECT * FROM [dbo].[User] WHERE UserID = @UserID",
            new { UserID = id }).FirstOrDefault();
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            int result = DapperManager.Execute(
                "MVC5TemplateServer",
                "DELETE FROM [dbo].[User] WHERE UserID = @UserID", new { UserID = id });
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = DapperManager.Query<User>("MVC5TemplateServer",
                "SELECT * FROM [dbo].[User] WHERE UserID = @UserID",
                new { UserID = id }).FirstOrDefault();
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserID,Password,FamilyName,FirstName,Birthday,Sex,MobilePhone,PostalCode,Prefectures,City,Address1,Address2,Apartment")] User user)
        {
            if (ModelState.IsValid)
            {
                int result = DapperManager.Execute("MVC5TemplateServer", "UPDATE [dbo].[User] SET Password = @Password, FamilyName = @FamilyName, FirstName = @FirstName, Birthday = @Birthday, Sex = @Sex, MobilePhone = @MobilePhone, PostalCode = @PostalCode, Prefectures = @Prefectures, City = @City, Address1 = @Address1, Address2 = @Address2, Apartment = @Apartment WHERE UserID = @UserID", user);
                return RedirectToAction("Index");
            }
            return View(user);
        }
    }
}

MVC5Template/MVC5Template/Areas/Sample/Controllers/ExceptionController.cs
using MVC5Template.Extensions;
using System;
using System.Web.Mvc;

namespace MVC5Template.Areas.Sample
{
    public class ExceptionController : SupportContoller
    {
        // GET: Sample/Exception
        public ActionResult Index()
        {
            return View();
        }

        // GET: Sample/
        public ActionResult Exception()
        {
            throw new Exception();
        }
    }
}

MVC5Template/MVC5Template/Areas/Sample/Controllers/JsonSampleController.cs
using MVC5Template.Extensions;
using System.Web.Mvc;

namespace MVC5Template.Areas.Sample.Controllers
{
    public class JsonSampleController : SupportContoller
    {
        // GET: Json
        public ActionResult Index()
        {
            return View();
        }
    }
}

MVC5Template/MVC5Template/Areas/Sample/Controllers/PluginController.cs
using MVC5Template.Extensions;
using System.IO;
using System.Web.Mvc;

namespace MVC5Template.Areas.Sample.Controllers
{
    public class PluginController : SupportContoller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Handsontable()
        {
            return View();
        }

        [HttpGet]
        public new ActionResult Session()
        {
            return View();
        }

        [HttpGet]
        public ActionResult ImageGallery()
        {
            string mapPath = Server.MapPath("/");
            string imageDir = mapPath + "/Content/Images/";
            string[] files = Directory.GetFiles(imageDir, "*.jpg", System.IO.SearchOption.AllDirectories);
            for(int i = 0; i < files.Length; i++)
            {
                var file = files[i];
                file = file.Replace(mapPath, "");
                files[i] = file;
            }
            return View(files);
        }

        [HttpGet]
        public ActionResult FileUpload()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Calendar()
        {
            return View();
        }
    }
}

MVC5Template/MVC5Template/Areas/Sample/Controllers/SampleHomeController.cs
using MVC5Template.Extensions;
using System.Web.Mvc;

namespace MVC5Template.Areas.Sample.Controllers
{
    public class SampleHomeController : SupportContoller
    {
        // GET: Sample/SampleHome
        public ActionResult Index()
        {
            return View();
        }
    }
}

MVC5Template/MVC5Template/Areas/Sample/Views/SampleHome/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = HttpContext.GetGlobalResourceObject("ResourceTitle", "Sample_SampleHome_Index_Title");
}

<div class="row">
    <div class="col-md-4">
        <h2>@HttpContext.GetGlobalResourceObject("ResourceTitle", "Sample_User_Index_Title")</h2>
        <p>@Html.Raw(HttpContext.GetGlobalResourceObject("ResourceMessage", "Sample_SampleHome_Index_User_About"))</p>
        <p>@Html.ActionLink(HttpContext.GetGlobalResourceObject("ResourceTitle", "Sample_User_Index_Title").ToString(), "Index", "User", new { area = "Sample" }, new { id = "lnkUser", @class = "btn btn-primary" })</p>
    </div>
    <div class="col-md-4">
        <h2>
            <a href="https://handsontable.com/" target="_blank">
                @HttpContext.GetGlobalResourceObject("ResourceTitle", "Sample_Plugin_Handsontable_Title")
            </a>
        </h2>
        <p>@Html.Raw(HttpContext.GetGlobalResourceObject("ResourceMessage", "Sample_SampleHome_Plugin_Handsontable_About"))</p>
        <p>@Html.ActionLink(HttpContext.GetGlobalResourceObject("ResourceTitle", "Sample_Plugin_Handsontable_Title").ToString(), "Handsontable", "Plugin", new { area = "Sample" }, new { id = "lnkHandsontable", @class = "btn btn-primary" })</p>
    </div>
    <div class="col-md-4">
        <h2>@HttpContext.GetGlobalResourceObject("ResourceTitle", "Sample_Plugin_Calendar_Title")</h2>
        <p>@Html.Raw(HttpContext.GetGlobalResourceObject("ResourceMessage", "Sample_SampleHome_Plugin_Calendar_About"))</p>
        <p>@Html.ActionLink(HttpContext.GetGlobalResourceObject("ResourceTitle", "Sample_Plugin_Calendar_Title").ToString(), "Calendar", "Plugin", new { area = "Sample" }, new { id = "lnkCalendar", @class = "btn btn-primary" })</p>
    </div>
    <div class="col-md-4">
        <h2>
            <a href="https://blueimp.github.io/Gallery/" target="_blank">
                @HttpContext.GetGlobalResourceObject("ResourceTitle", "Sample_Plugin_ImageGallery_Title")
            </a>
        </h2>
        <p>@Html.Raw(HttpContext.GetGlobalResourceObject("ResourceMessage", "Sample_SampleHome_Plugin_ImageGallery_About"))</p>
        <p>@Html.ActionLink(HttpContext.GetGlobalResourceObject("ResourceTitle", "Sample_Plugin_ImageGallery_Title").ToString(), "ImageGallery", "Plugin", new { area = "Sample" }, new { id = "lnkImageGallery", @class = "btn btn-primary" })</p>
    </div>
    <div class="col-md-4">
        <h2>@HttpContext.GetGlobalResourceObject("ResourceTitle", "Sample_FormsAuthentication_Index_Title")</h2>
        <p>@Html.Raw(HttpContext.GetGlobalResourceObject("ResourceMessage", "Sample_SampleHome_FormsAuthentication_Index_About"))</p>
        <p>@Html.ActionLink(HttpContext.GetGlobalResourceObject("ResourceTitle", "Sample_FormsAuthentication_Index_Title").ToString(), "Index", "FormsAuthentication", new { area = "Sample" }, new { id = "lnkFormsAuthentication", @class = "btn btn-primary" })</p>
    </div>
    <div class="col-md-4">
        <h2>@HttpContext.GetGlobalResourceObject("ResourceTitle", "Sample_Plugin_Session_Title")</h2>
        <h2></h2>
        <p>@Html.Raw(HttpContext.GetGlobalResourceObject("ResourceMessage", "Sample_SampleHome_Plugin_Session_About"))</p>
        <p>@Html.ActionLink(HttpContext.GetGlobalResourceObject("ResourceTitle", "Sample_Plugin_Session_Title").ToString(), "Session", "Plugin", new { area = "Sample" }, new { id = "lnkSession", @class = "btn btn-primary" })</p>
    </div>
    <div class="col-md-4">
        <h2>@HttpContext.GetGlobalResourceObject("ResourceTitle", "Sample_ResultSample_Index_Title")</h2>
        <p>@Html.Raw(HttpContext.GetGlobalResourceObject("ResourceMessage", "Sample_SampleHome_ResultSample_Index_About"))</p>
        <p>@Html.ActionLink(HttpContext.GetGlobalResourceObject("ResourceTitle", "Sample_ResultSample_Index_Title").ToString(), "Index", "ResultSample", new { area = "Sample" }, new { id = "lnkResultSample", @class = "btn btn-primary" })</p>
    </div>
    <div class="col-md-4">
        <h2>@HttpContext.GetGlobalResourceObject("ResourceTitle", "Sample_JsonSample_Index_Title")</h2>
        <p>@Html.Raw(HttpContext.GetGlobalResourceObject("ResourceMessage", "Sample_SampleHome_JsonSample_Index_About"))</p>
        <p>@Html.ActionLink(HttpContext.GetGlobalResourceObject("ResourceTitle", "Sample_JsonSample_Index_Title").ToString(), "Index", "JsonSample", new { area = "Sample" }, new { id = "lnkJsonSample", @class = "btn btn-primary" })</p>
    </div>
    <div class="col-md-4">
        <h2>@HttpContext.GetGlobalResourceObject("ResourceTitle", "Sample_Exception_Index_Title")</h2>
        <p>@Html.Raw(HttpContext.GetGlobalResourceObject("ResourceMessage", "Sample_SampleHome_Exception_Index_About"))</p>
        <p>@Html.ActionLink(HttpContext.GetGlobalResourceObject("ResourceTitle", "Sample_Exception_Index_Title").ToString(), "Index", "Exception", new { area = "Sample" }, new { id = "lnkException", @class = "btn btn-primary" })</p>
    </div>
    <div class="col-md-4">
        <h2>@HttpContext.GetGlobalResourceObject("ResourceTitle", "Sample_BulletinBoard_Index_Title")</h2>
        <p>@Html.Raw(HttpContext.GetGlobalResourceObject("ResourceMessage", "Sample_SampleHome_BulletinBoard_Index_About"))</p>
        <p>@Html.ActionLink(HttpContext.GetGlobalResourceObject("ResourceTitle", "Sample_BulletinBoard_Index_Title").ToString(), "Index", "BulletinBoard", new { area = "Sample" }, new { id = "lnkBulletinBoard", @class = "btn btn-primary" })</p>
    </div>

</div>